### ISSUE TITLE
Remove `_epoch` parameter from `_migrateToV2` functions

### ISSUE THREAD

**Issue by mudgen** [aavegotchi/ghst-staking#11]
A user can _only_ be migrated to the current epoch (s.currentEpoch).

Remove the `_epoch` parameters from these two functions:
https://github.com/aavegotchi/ghst-staking/blob/25c954121c89a8286a46faa93a667d6eb6944969/contracts/facets/StakingFacet.sol#L380

https://github.com/aavegotchi/ghst-staking/blob/25c954121c89a8286a46faa93a667d6eb6944969/contracts/facets/StakingFacet.sol#L365

--

Change this code in the `_migrateToV2` function:
https://github.com/aavegotchi/ghst-staking/blob/25c954121c89a8286a46faa93a667d6eb6944969/contracts/facets/StakingFacet.sol#L394

To this:
```
_updateFrens(_account, s.currentEpoch);
```

**Comment by cinnabarhorse** [comment]
Yes you are right, when a user is migrated their FRENS are updated using the old pools, not the new epoch pools.
