### ISSUE TITLE
Delete lines in `withdrawFromPool` function

### ISSUE THREAD

**Issue by mudgen** [aavegotchi/ghst-staking#13]
These lines from the `withdrawFromPool` function should be deleted:

https://github.com/aavegotchi/ghst-staking/blob/7543933cc9aa4bf983c845cb2c5335c02b2dca0a/contracts/facets/StakingFacet.sol#L358-L361

**Comment by cinnabarhorse** [comment]
Yes I believe these can safely be removed. We'll remove and write a test to cover. Thanks.
