### ISSUE TITLE
Possible Integer Overflow 

### ISSUE THREAD

**Issue by mudgen** [aavegotchi/ghst-staking#4]
@spalladino reported the following:

> Just took a look at the updated frens function. It's indeed much simpler, though there's a risk for overflow depending on what values you get.

> The catch is that this operation gets done on a uint96 value (uniV2PoolTokens), not on a uint256 as the result type.
`frens_ += ((account.uniV2PoolTokens * 100) * timePeriod) / 86400;`

> You can test it out with a sample contract like this one:
```Solidity
contract Foo {
    function foo(uint104 initial, uint96 value,  uint32 lastUpdate) external view returns (uint256 res) {
        uint256 period = block.timestamp - lastUpdate;
        res = initial;
        res += ((value * 100) * period) / 86400;
    }

    function bar(uint104 initial, uint96 value,  uint32 lastUpdate) external view returns (uint256 res) {
        uint256 period = block.timestamp - lastUpdate;
        res = initial;
        res += ((uint256(value) * 100) * period) / 86400;
    }
}
```
> Note the cast of the uint96 value to uint256 in bar. Calling both functions with the values:
```
initial=0
value=792281625142643400000000000 (2**96/100)
lastUpdate=1599400006 (1 month ago)
```
> Returns an incorrect value for foo (which is the implementation now in frens) and a correct one in bar (with the patch to cast value, or uniV2PoolTokens in your case) to uint256 before operating on it. 

---

The above was tested and verified. The only overflow point is `(account.uniV2PoolTokens * 100)`.  The result of an analysis of the effect of this is the following:

For the expression to overflow the user must have 792,281,630 uniV2PoolTokens tokens (or LP tokens)  which is practically impossible. 

Currently the cost of 1 GHST/ETH LP token is $45.5 USD. So the cost of 792,281,630 LP tokens would be 36 billion USD.

However the expression was not intended to work the way as reported in this issue, and technically the problem is possible though unlikely.  

The `frens` function has been updated to cast `account.uniV2PoolTokens` to `uint256`.

@spalladino's input on this is valuable and it is valuable that he is looking at the contracts.   Currently discussing a payout amount.

**Comment by spalladino** [comment]
> The only overflow point is (account.uniV2PoolTokens * 100)

I think the overflow point includes the multiplication by `period` as well, which is expressed in seconds. This means that the threshold for hitting the overflow would depend on the time since last update as well. For the case of 1 week, it's 604800, which means that 36B USD turns into ~60K USD, which is much more attainable.

**Comment by mudgen** [comment]
@spalladino Thanks for your input on this but I don't find that to be the case because `period` (or `timePeriod`) is a `uint256` which upcasts the expression to `uint256`.

Here's my tests on this:
```Solidity
contract Foo {

    function foo() external view returns (uint256 res) {
        uint256 period = 1599400006; // 1 month
        uint96 value = type(uint96).max / 100;
        res = ((value * 100) * period) / 86400;
    }

    function bar() external view returns (uint256 res) {
        uint256 period = 1599400006; // 1 month
        uint96 value = type(uint96).max / 100;
        res = ((uint(value) * 100) * period) / 86400;
    }
}
```

Both of these functions return the value: `1466638004637538849915511801748653`.   The `period` variable upcasts the expression so that the result can be beyond the max of `uint96` which is `79228162514264337593543950335`.

**Comment by spalladino** [comment]
Good point, I missed that cast. Disregard my comment above then.
