### ISSUE TITLE
epoch branch review

### ISSUE THREAD

**Issue by mudgen** [aavegotchi/ghst-staking#9]
Might want to add an external function that enables one or more epochs to be updated for an address but not all epochs at the same time.  This is an escape hatch for the unlikely possibility of hitting a block gas size limit in the future.

---

Might want to add a require statement to the stakeIntoPool function that checks that the _poolContractAddress is an actual correct address to a pool. If it is not then the transaction will fail on minting the stkTokenAddress but the error message might be obscure
**But also,  if you ever removed a pool from a new epoch,  someone could still stake into it because there is no check that _poolContractAddress  is valid for the current epoch.**

---

In this function:
```
function stakeIntoPool(address _poolContractAddress, uint256 _amount) public {
        address sender = LibMeta.msgSender();
        updateFrens(sender);
        if (!s.accounts[sender].hasMigrated) _migrateToV2(sender);

        //Transfer the LP tokens into the Diamond
        LibERC20.transferFrom(_poolContractAddress, sender, address(this), _amount);

        //Credit the user's with their new LP token balance
        s.accounts[sender].accountStakedTokens[_poolContractAddress] += _amount;

        if (_poolContractAddress == s.ghstContract) {
            s.accounts[sender].ghst += uint96(_amount);
            //Do nothing for original GHST contract
        } else if (_poolContractAddress == s.poolContract) {
            s.accounts[sender].ghstStakingTokens += _amount;
            s.ghstStakingTokensTotalSupply += _amount;
            emit Transfer(address(0), sender, _amount);
        } else {
            //Use mintable for minting stkGHST- token
            address stkTokenAddress = s.pools[_poolContractAddress].receiptToken;
            IERC20Mintable(stkTokenAddress).mint(sender, _amount);
        }

        emit StakeInEpoch(sender, _poolContractAddress, s.currentEpoch, _amount);
    }
```

I suggest moving `LibERC20.transferFrom(_poolContractAddress, sender, address(this), _amount); ` to above the emit StakeInEpoch  line.    Because where it currently is opens it up to reentry attack,  though it seems unlikely because _poolContractAddress  is probably a safe contract.   But more secure is better and this is an easy change. In general it is better to put calls to external contracts after state changes and not before.

---

In the withdrawFromPool function these two requires do the same thing.  Only the first one is needed.
```
require(stakedBalance >= _amount, "StakingFacet: Can't withdraw more tokens than staked");
require(s.accounts[sender].accountStakedTokens[_poolContractAddress] >= _amount, "Can't withdraw more poolTokens than in account");
```

---

This line is not needed in the `stakeIntoPool` function because `s.accounts[sender].ghst` is not used after migration:
`s.accounts[sender].ghst += uint96(_amount);`

These lines are not needed in the `stakeIntoPool` function because `s.accounts[sender].poolTokens` is not used after migration:
```
uint256 accountPoolTokens = s.accounts[sender].poolTokens;
require(accountPoolTokens >= _amount, "Can't withdraw more poolTokens than in account");

s.accounts[sender].poolTokens -= _amount;
```

---

**Comment by cinnabarhorse** [comment]
Thanks for the review. I've made the specified changes in this branch: https://github.com/aavegotchi/ghst-staking/compare/epoch...epoch-fixes
